name: Deploy-DAD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Changes
        run: git pull
      - name: Build VUE
        run: cd laravel-vue && npm run prod
      - name: Restart Socket
        run: cd socket && forever restart index.js